name: Release binance

on:
  push:
    tags:
      - binance_v*

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com
          scope: '@hastobegood'
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Build code
        run: yarn build
      - name: Run linter
        run: yarn lint
      - name: Run tests
        run: yarn test
      - name: Publish version
        run: yarn publish:binance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
